"""Build the overlay's embedded UI font subset (entered through `subset.ps1`).

Why this exists
---------------
The overlay's DirectWrite text (size label, magnifier info panel, the level hints) draws with
`HarmonyOS Sans SC` — an 8.5 MB system font reduced here to the ~60 glyphs those strings
actually use, then embedded with `include_bytes!` so no machine needs the font installed.

That reduction is a *hard allowlist*: a character that is not in the subset does not fail
anywhere. DirectWrite falls back per glyph, so the string quietly renders half in HarmonyOS and
half in Microsoft YaHei (or as tofu if the fallback is refused). Nothing in `cargo test` notices;
it is visible only on screen.

So the character set is the characters of **the strings the overlay draws and nothing else**:

* `subfont/drawn-text.txt` is generated from `overlay_drawn_strings()` in `win/d2d.rs` — one list in
  Rust, next to the drawing code, assembled from the text's producers. Scanning the whole crate
  instead would drag in characters that are never painted (a Chinese literal in a storage test, an
  em dash in a log message) and the font exists to be small;
* printable ASCII is added whole (see below), because the panel draws computed text;
* and the text-drawing files are then **guarded**: every non-ASCII literal in a file that calls the
  DirectWrite text API has to be accounted for by that list, so a string drawn inline cannot slip
  past it unnoticed.

Run this through `subfont/subset.ps1`: it regenerates `drawn-text.txt` first (the list is Rust's
answer, not something to maintain by hand, and this script refuses to build from a stale one).
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.subset import main as subset_main

from rust_literals import literals_with_lines

ROOT = Path(__file__).resolve().parent.parent
# The overlay is the only thing that draws text, and since docs/23 T1.5 it lives in the
# capture crate. Widen this if another crate ever starts drawing.
SCAN_ROOT = ROOT / "crates" / "snapclip-capture" / "src"
DRAWN = ROOT / "subfont" / "drawn-text.txt"
SOURCE = ROOT / "refer" / "HarmonyOS_SansSC_Regular.ttf"
BUILT = ROOT / "subfont" / "harmonyos-sans-sc-subset.ttf"
# The exact path `crates/snapclip-capture/src/windows/win/d2d.rs` embeds with include_bytes!.
INSTALLED = ROOT / "crates" / "snapclip-capture" / "assets" / "harmonyos-sans-sc-subset.ttf"

# Tables the renderer never reads; dropping them keeps the blob small (see the original script).
DROP_TABLES = (
    "DSIG,hdmx,VDMX,LTSH,PCLT,gasp,meta,kern,GPOS,GSUB,GDEF,BASE,JSTF,MATH,prep,fpgm,cvt"
)


# A file "draws text" if it calls one of these; its literals are then part of the contract.
TEXT_APIS = ("DrawText(", "CreateTextFormat(", "CreateTextLayout(")


def drawn_strings() -> list[str]:
    """The strings the overlay draws, as generated by `win/d2d.rs`."""
    if not DRAWN.exists():
        raise SystemExit(f"missing {DRAWN.relative_to(ROOT)} — run subfont/subset.ps1")
    newest_source = max(path.stat().st_mtime for path in SCAN_ROOT.rglob("*.rs"))
    if DRAWN.stat().st_mtime < newest_source:
        raise SystemExit(
            f"{DRAWN.relative_to(ROOT)} is older than the Rust sources — run subfont/subset.ps1, "
            "which regenerates it (a stale list builds a font that is missing glyphs)"
        )
    return [
        line
        for line in DRAWN.read_text(encoding="utf-8").splitlines()
        if line and not line.startswith("//")
    ]


def guard_text_drawing_files(required: set[int]) -> None:
    """Any non-ASCII literal in a text-drawing file must be part of the drawn-text list."""
    offenders: list[str] = []
    for path in sorted(SCAN_ROOT.rglob("*.rs")):
        source = path.read_text(encoding="utf-8")
        if not any(api in source for api in TEXT_APIS):
            continue
        for line, literal in literals_with_lines(source):
            for char in literal:
                if ord(char) > 0x7F and ord(char) not in required:
                    offenders.append(
                        f"{path.relative_to(ROOT)}:{line}: {char!r} (U+{ord(char):04X}) in {literal!r}"
                    )
    if offenders:
        listing = "\n  ".join(offenders)
        raise SystemExit(
            "these characters are written in a file that draws text but are not in "
            f"`overlay_drawn_strings()`:\n  {listing}\n"
            "Add the string to that list in win/d2d.rs (or drop the literal if it is not drawn)."
        )


def required_codepoints() -> set[int]:
    """Printable ASCII, plus every character of the strings the overlay draws."""
    # The Latin side is taken whole. The panel draws *computed* text — colour values, coordinates,
    # sizes, percentages — so no scan and no list can enumerate the digits and hex letters that will
    # appear: the first version of this pipeline used an example-derived list and was missing `3`.
    # 95 glyphs cost ~4 KB and remove the entire class of bug.
    codes = set(range(0x20, 0x7F))
    strings = drawn_strings()
    for text in strings:
        codes |= {ord(char) for char in text}
    non_ascii = sum(1 for code in codes if code > 0x7F)
    print(f"drawn:    {len(strings)} strings from {DRAWN.relative_to(ROOT)}, "
          f"{non_ascii} non-ASCII characters among them")
    guard_text_drawing_files(codes)
    return codes


def covered_codepoints(path: Path) -> set[int]:
    """Codepoints a font's cmap answers with a real glyph."""
    font = TTFont(path)
    covered: set[int] = set()
    for table in font["cmap"].tables:
        for code, name in table.cmap.items():
            if name and name != ".notdef":
                covered.add(code)
    return covered


def main() -> int:
    if not SOURCE.exists():
        raise SystemExit(f"missing source font: {SOURCE}")
    required = required_codepoints()
    unicodes = ",".join(f"U+{code:04X}" for code in sorted(required))
    print(f"required: {len(required)} codepoints")

    subset_main(
        [
            str(SOURCE),
            f"--unicodes={unicodes}",
            f"--output-file={BUILT}",
            "--layout-features=",
            "--no-hinting",
            "--desubroutinize",
            "--name-IDs=1,2",
            "--name-languages=0x409",
            f"--drop-tables+={DROP_TABLES}",
            # Keep .notdef so a missing glyph is visible as tofu rather than invisible.
            "--notdef-glyph",
            "--recommended-glyphs",
        ]
    )

    # The gate: the artifact has to cover what the code draws *now*. Without this the failure
    # mode is a half-HTML-ish string on screen that no test and no log mentions.
    covered = covered_codepoints(BUILT)
    missing = sorted(required - covered)
    if missing:
        listing = " ".join(f"U+{code:04X} {chr(code)!r}" for code in missing)
        raise SystemExit(f"the subset does not cover {len(missing)} required glyph(s): {listing}")
    print(f"built:    {BUILT.relative_to(ROOT)}  {BUILT.stat().st_size / 1024:.1f} KB  "
          f"({len(covered)} codepoints, all required ones covered)")

    INSTALLED.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(BUILT, INSTALLED)
    print(f"installed: {INSTALLED.relative_to(ROOT)}  "
          f"({INSTALLED.stat().st_size / 1024:.1f} KB, read by include_bytes!)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
